apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-backup
  labels:
    disk: backup
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.94.5
    path: "/srv/exports/volumes/sql-instance-2/backup"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-backup
spec:
  selector:
    matchLabels:
      disk: backup
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
      hostname:
          sql01
      containers:
      - name: mssql
        image: 'mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04'
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 3Gi
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: 'Y'
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: SA_PASSWORD 
        - name: MSSQL_AGENT_ENABLED
          value: 'true'
        - name: MSSQL_DATA_DIR
          value: '/data'
        - name: MSSQL_LOG_DIR
          value: '/log'
        volumeMounts:
        - name: system
          mountPath: /var/opt/mssql
        - name: data
          mountPath: /data
        - name: log
          mountPath: /log
        - name: backup
          mountPath: /backup
      volumes:
      - name: system
        persistentVolumeClaim:
          claimName: pvc-nfs-system
      - name: data
        persistentVolumeClaim:
          claimName: pvc-nfs-data
      - name: log
        persistentVolumeClaim:
          claimName: pvc-nfs-log
      - name: backup
        persistentVolumeClaim:
          claimName: pvc-nfs-backup
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-deployment
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 31433
      targetPort: 1433
  type: NodePort