FROM mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
WORKDIR /mywebapp
COPY ./mywebapp/ .
RUN PowerShell Install-WindowsFeature NET-Framework-45-ASPNET; \
    Install-WindowsFeature Web-Asp-Net45; \
    Import-Module WebAdministration; \
    New-WebApplication 'mywebapp' -Site 'Default Web Site' -ApplicationPool 'DefaultAppPool' -PhysicalPath "C:\mywebapp"

