# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
#   config.vbguest.auto_update = true
#   config.vbguest.auto_reboot = true
  config.vm.box = "stefanscherer/windows_10"
  config.vm.boot_timeout = 600

  # windows
  config.vm.guest = :windows
  config.windows.halt_timeout = 60
  config.windows.set_work_network = true

  # winrm
  config.vm.communicator = 'winrm'
  config.winrm.username = 'vagrant'
  config.winrm.password = 'vagrant'
  # https://github.com/hashicorp/vagrant/issues/6430
  config.winrm.retry_limit = 30
  config.winrm.retry_delay = 10

  config.vm.network :forwarded_port, guest: 5985, host: 14985, id: 'winrm', auto_correct: true
  config.vm.network :forwarded_port, guest: 3389, host: 14389, id: 'rdp', auto_correct: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = 4096
    vb.cpus = 2
    vb.linked_clone = true
    vb.customize ['modifyvm', :id, '--vram', '128']
  end

  config.vm.provision "shell", inline: <<-SHELL
    Get-Service wuauserv | Stop-Service -PassThru | Set-Service -StartupType Disabled
    cscript c:/windows/system32/slmgr.vbs /rearm | Out-Null
    Set-ExecutionPolicy Bypass -Scope Process -Force
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
    iex (irm https://chocolatey.org/install.ps1)

    $null = choco install MicrosoftWindowsPowerShellV2 -s windowsfeatures -y
    Get-Service wuauserv | Set-Service -StartupType Manual
    DISM /Online /Enable-Feature /FeatureName:NetFx3 /All
    Get-Service wuauserv | Stop-Service -PassThru | Set-Service -StartupType Disabled
    choco install git -y --no-progress
    Install-PackageProvider -Name NuGet -Force
    Install-Module posh-git -Force
  SHELL
end
